### ISSUE TITLE
Running total timer for PECM operation time

### ISSUE THREAD

**Issue by mbromley-voxel** [dmherrington/ECM-Control-System#52]
Include a timer that tracks the total amount of time the PECM machine is operating.

Definition of operating: A machine profile is being executed.

Originally it was suggested that it could be when the linear motor was moving, but there are some profiles run that do not utilize the linear motor motion for machining.

Nice to have - an email report or text file on the drop box of tracked metrics for the month.  The total amount of operating time would be one of the metrics included (others not yet defined).

**Comment by majorpr13** [comment]
This has been completed in the current branches of code.
